const products = [
  {
    id: 1,
    category: 'tires',
    brand: 'Continental',
    title: 'VanContact Eco',
    price: 136.99,
    rating: 5,
    reviews: 412,
    season: 'Summer',
    year: '2026',
    vehicleType: 'Standard car',
    size: '185/65 R15',
    image: 'https://images.unsplash.com/photo-1599406086771-47fb2bf12a7d?auto=format&fit=crop&q=80&w=400',
    description: 'A summer tire perfectly adapted for light commercial vehicles and vans. Optimized rolling resistance for excellent fuel efficiency.'
  },
  {
    id: 2,
    category: 'tires',
    brand: 'Bridgestone',
    title: 'Weather Control A005',
    price: 140.99,
    rating: 4.8,
    reviews: 632,
    season: 'All year',
    year: '2026',
    vehicleType: 'Standard car',
    size: '205/55 R16',
    image: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&q=80&w=400',
    description: 'The all-season touring tire built to help you master your journey, no matter the season. Best-in-class wet grip.'
  },
  {
    id: 3,
    category: 'tires',
    brand: 'Michelin',
    title: 'Agilis CrossClimate',
    price: 128.99,
    rating: 5,
    reviews: 567,
    season: 'All year',
    year: '2025',
    vehicleType: 'Delivery / Van',
    size: '195/70 R15',
    image: 'https://images.unsplash.com/photo-1600705054366-06eb1af52e1c?auto=format&fit=crop&q=80&w=400',
    description: 'Safety in all weather conditions, excellent mileage, and robustness. A highly durable commercial tire.'
  },
  {
    id: 4,
    category: 'tires',
    brand: 'Michelin',
    title: 'Pilot Sport 4 SUV',
    price: 108.99,
    rating: 4.5,
    reviews: 235,
    season: 'Summer',
    year: '2024',
    vehicleType: '4x4',
    size: '225/60 R18',
    image: 'https://images.unsplash.com/photo-1590487538946-bdeb26fba471?auto=format&fit=crop&q=80&w=400',
    description: 'Exceptional grip and safety: 1st in dry and wet braking. Specially designed for premium SUVs.'
  },
  {
    id: 5,
    category: 'tires',
    brand: 'Pirelli',
    title: 'P Zero Winter',
    price: 189.99,
    rating: 4.9,
    reviews: 890,
    season: 'Winter',
    year: '2026',
    vehicleType: 'Performance',
    size: '245/45 R19',
    image: 'https://images.unsplash.com/photo-1579731454508-3abeb5c83fbf?auto=format&fit=crop&q=80&w=400',
    description: 'The highest level of winter performance codeveloped with the best car makers. Unrivalled snow control.'
  },
  {
    id: 6,
    category: 'tires',
    brand: 'Goodyear',
    title: 'Eagle F1 Asymmetric 5',
    price: 155.00,
    rating: 4.7,
    reviews: 420,
    season: 'Summer',
    year: '2025',
    vehicleType: 'Standard car',
    size: '235/40 R18',
    image: 'https://images.unsplash.com/photo-1598287515152-4424754ac00a?auto=format&fit=crop&q=80&w=400',
    description: 'Luxurious comfort with superior wet braking. Refined styling for the true enthusiast.'
  },
  {
    id: 7,
    category: 'tires',
    brand: 'Falken',
    title: 'Azenis FK510',
    price: 115.50,
    rating: 4.3,
    reviews: 180,
    season: 'Summer',
    year: '2024',
    vehicleType: 'Performance',
    size: '225/45 R17',
    image: 'https://images.unsplash.com/photo-1610444585141-831e7844cc96?auto=format&fit=crop&q=80&w=400',
    description: 'Advanced 4D Nano Design tread compound. Maximized grip and wear performance for sports cars.'
  },
  {
    id: 8,
    category: 'tires',
    brand: 'Hankook',
    title: 'Winter i*cept evo3',
    price: 132.00,
    rating: 4.6,
    reviews: 315,
    season: 'Winter',
    year: '2026',
    vehicleType: 'Standard car',
    size: '205/55 R16',
    image: 'https://images.unsplash.com/photo-1517524956381-8ed0cd19bf08?auto=format&fit=crop&q=80&w=400',
    description: 'Perfect winter performance under any condition. Excellent snow traction and braking.'
  },
  {
    id: 9,
    category: 'tires',
    brand: 'Dunlop',
    title: 'Sport Maxx RT2',
    price: 148.99,
    rating: 4.4,
    reviews: 210,
    season: 'Summer',
    year: '2025',
    vehicleType: 'Performance',
    size: '245/40 R18',
    image: 'https://images.unsplash.com/photo-1590487373801-9a997d4c2edb?auto=format&fit=crop&q=80&w=400',
    description: 'A champion in grip and steering precision. Designed to deliver an engaging driving experience.'
  },
  {
    id: 10,
    category: 'tires',
    brand: 'Yokohama',
    title: 'Geolandar A/T G015',
    price: 165.00,
    rating: 4.8,
    reviews: 540,
    season: 'All year',
    year: '2026',
    vehicleType: '4x4',
    size: '265/70 R17',
    image: 'https://images.unsplash.com/photo-1563200781-54de5c2a1ce3?auto=format&fit=crop&q=80&w=400',
    description: 'The ultimate all-terrain tire built to conquer any surface. Long-lasting treadwear.'
  },
  {
    id: 11,
    category: 'rims',
    brand: 'BBS',
    title: 'Super RS',
    price: 1250.00,
    rating: 5,
    reviews: 120,
    season: 'All year',
    year: '2026',
    vehicleType: 'Performance',
    size: '19 inch',
    image: 'https://images.unsplash.com/photo-1601362840469-51e4d8d58785?auto=format&fit=crop&q=80&w=400',
    description: 'Classic multi-spoke design reborn in a modern 2-piece forged configuration.'
  },
  {
    id: 12,
    category: 'rims',
    brand: 'Enkei',
    title: 'RPF1',
    price: 345.50,
    rating: 4.9,
    reviews: 840,
    season: 'All year',
    year: '2026',
    vehicleType: 'Performance',
    size: '18 inch',
    image: 'https://images.unsplash.com/photo-1581452292770-571216d1ba56?auto=format&fit=crop&q=80&w=400',
    description: 'Legendary lightweight racing wheel developed using Enkei’s MAT process.'
  },
  {
    id: 13,
    category: 'accessories',
    brand: 'Michelin',
    title: 'Digital Tire Pressure Gauge',
    price: 24.99,
    rating: 4.5,
    reviews: 215,
    season: 'All year',
    year: '2026',
    vehicleType: 'Standard car',
    size: 'Universal',
    image: 'https://images.unsplash.com/photo-1605230985854-ce523c961ebd?auto=format&fit=crop&q=80&w=400',
    description: 'Accurately measure and maintain ideal tire pressure to enhance safety and fuel efficiency.'
  },
  {
    id: 14,
    category: 'accessories',
    brand: 'Meguiar',
    title: 'Ultimate Tire Shine',
    price: 15.99,
    rating: 4.8,
    reviews: 932,
    season: 'All year',
    year: '2026',
    vehicleType: 'Standard car',
    size: '15 oz',
    image: 'https://images.unsplash.com/photo-1622177301033-b152ebba9261?auto=format&fit=crop&q=80&w=400',
    description: 'Deep, dark, and glossy synthetic polymer formula provides a long-lasting wet look.'
  }
];
